require "user.alpha-nvim"
require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.cmp"
require "user.lsp"
require "user.telescope"
require "user.treesitter"
require "user.comment"
require "user.gitsigns"
require "user.nvim-tree"
-- require "user.bufferline"
require "user.colorscheme"
require "user.autosave"
-- require "user.blamer"
require "user.lualine"
require "user.flog"
-- require "user.startify"
require "user.colorized"
require "user.fzf-lua"
